/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HoverContainer: typeof import('./../../components/HoverContainer.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulerLine: typeof import('./../../components/icons/RulerLine.vue')['default']
  }
}
